apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employeebook-autoscaler  # Name of the HorizontalPodAutoscaler
spec:
  scaleTargetRef:  # Reference to the target resource to scale
    apiVersion: apps/v1  # API version of the target resource
    kind: Deployment  # Kind of the target resource
    name: java-employeebook-backend  # Name of the target resource (Deployment)
  minReplicas: 3  # Minimum number of pod replicas
  maxReplicas: 5  # Maximum number of pod replicas
  metrics:  # Metrics to use for scaling
    - type: Resource  # Type of metric (resource-based)
      resource:  # Resource metric specification
        name: cpu  # Resource to monitor (CPU)
        target:  # Target specification
          type: Utilization  # Target type (utilization percentage)
          averageUtilization: 70  # Target average utilization percentage
    - type: Resource  # Type of metric (resource-based)
      resource:  # Resource metric specification
        name: memory  # Resource to monitor (Memory)
        target:  # Target specification
          type: Utilization  # Target type (utilization percentage)
          averageUtilization: 80  # Target average utilization percentage for memory
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30


